[workspace]
members = ["contracts/always_success","contracts/spawn_demo", "contracts/loop_contract"]
exclude = ["tests"]

[profile.release]
overflow-checks = true
strip = true
opt-level = 's'
lto = false
codegen-units = 1
