[package]
name = "tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-testtool = { git = "https://github.com/nervosnetwork/ckb-testtool", branch = "main" }
bytes = "1.6.0"
serde_json = "1.0.117"
