name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  contract-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        id: runtest
        run: |
          bash prepare.sh
          bash build.sh
          bash test.sh